initial commit
AlexsisMoskovchuk/cinema-app pull request #1
Opened 2022-01-04 15:52 UTC by AlexsisMoskovchuk

2022-01-04 17:15 UTC, issugy requested changes

2022-01-04 17:15 UTC, issugy commented on checkstyle.xml
> +</module>
add empty line

2022-01-04 17:15 UTC, issugy commented on pom.xml
> +    <artifactId>diamond</artifactId>
add informative group and artifact ids

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/dao/impl/ShoppingCartDaoImpl.java
> +
redundant empty line

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/dao/impl/TicketDaoImpl.java
> +
redundant empty line

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/exception/AuthenticationException.java
> +
redundant empty line

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/dao/impl/UserDaoImpl.java
> +            throw new DataProcessingException("Can't insert to DB user: "
lets make messages of exceptions be consistent

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/model/MovieSession.java
> +    private CinemaHall cinemaHall;
add name for column

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/model/MovieSession.java
> +    private LocalDateTime showTime;
same

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/model/ShoppingCart.java
> +    private List<Ticket> tickets;
add names for table and columns

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/model/Ticket.java
> +
redundant empty line

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/model/Ticket.java
> +    private MovieSession movieSession;
add name for column

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/model/Ticket.java
> +
redundant empty line

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/model/Ticket.java
> +
redundant empty line

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/security/AuthenticationServiceImpl.java
> +    }
where do u throw registration exception ?

2022-01-04 17:15 UTC, issugy commented on src/main/java/cinema/util/HashUtil.java
> +public class HashUtil {
add private default constructor

2022-01-04 17:15 UTC, issugy commented on src/test/java/core/basesyntax/HelloWorldTest.java
> +}
remove this file

2022-01-05 09:27 UTC, issugy requested changes
fix all previous comments

2022-01-05 09:27 UTC, issugy commented on pom.xml
>      <artifactId>diamond</artifactId>
what about artifact id ?

2022-01-05 09:39 UTC, AlexsisMoskovchuk commented on pom.xml
>      <artifactId>diamond</artifactId>
fixed

2022-01-05 10:42 UTC, issugy approved these changes

2022-01-05 11:26 UTC, merged